# Generated by Django 4.2.3 on 2023-07-04 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videos',
            name='video_image',
            field=models.ImageField(upload_to='image/'),
        ),
    ]
